[package]
name = "rust-periphery"
version = "0.1.0"
authors = ["Brendan Arciszewski <git@brendanarciszewski.ca>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
cc = "^1.0"

[dependencies]
